name: UniGuru-Guard

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dev requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run flake8
        run: flake8
      - name: Run tests
        run: pytest -q
      - name: CI grep (forbidden patterns)
        run: python scripts/ci_grep.py
      - name: Boundary tag check
        run: python scripts/check_boundary_tags.py

